version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
  assignees:
  - rudotriton
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: stylelint
    versions:
    - 13.8.0
    - 13.9.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
